# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /mnt/opt/cmake-3.4.3-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /mnt/opt/cmake-3.4.3-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/q/ClionProjects/untitled1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/q/ClionProjects/untitled1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/mnt/opt/cmake-3.4.3-Linux-x86_64/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/mnt/opt/cmake-3.4.3-Linux-x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/q/ClionProjects/untitled1/CMakeFiles /home/q/ClionProjects/untitled1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/q/ClionProjects/untitled1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

ForwardSearchFifoQueue.o: ForwardSearchFifoQueue.cpp.o

.PHONY : ForwardSearchFifoQueue.o

# target to build an object file
ForwardSearchFifoQueue.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ForwardSearchFifoQueue.cpp.o
.PHONY : ForwardSearchFifoQueue.cpp.o

ForwardSearchFifoQueue.i: ForwardSearchFifoQueue.cpp.i

.PHONY : ForwardSearchFifoQueue.i

# target to preprocess a source file
ForwardSearchFifoQueue.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ForwardSearchFifoQueue.cpp.i
.PHONY : ForwardSearchFifoQueue.cpp.i

ForwardSearchFifoQueue.s: ForwardSearchFifoQueue.cpp.s

.PHONY : ForwardSearchFifoQueue.s

# target to generate assembly for a file
ForwardSearchFifoQueue.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ForwardSearchFifoQueue.cpp.s
.PHONY : ForwardSearchFifoQueue.cpp.s

Parameters.o: Parameters.cpp.o

.PHONY : Parameters.o

# target to build an object file
Parameters.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Parameters.cpp.o
.PHONY : Parameters.cpp.o

Parameters.i: Parameters.cpp.i

.PHONY : Parameters.i

# target to preprocess a source file
Parameters.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Parameters.cpp.i
.PHONY : Parameters.cpp.i

Parameters.s: Parameters.cpp.s

.PHONY : Parameters.s

# target to generate assembly for a file
Parameters.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Parameters.cpp.s
.PHONY : Parameters.cpp.s

Search.o: Search.cpp.o

.PHONY : Search.o

# target to build an object file
Search.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Search.cpp.o
.PHONY : Search.cpp.o

Search.i: Search.cpp.i

.PHONY : Search.i

# target to preprocess a source file
Search.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Search.cpp.i
.PHONY : Search.cpp.i

Search.s: Search.cpp.s

.PHONY : Search.s

# target to generate assembly for a file
Search.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Search.cpp.s
.PHONY : Search.cpp.s

SearchFileReader.o: SearchFileReader.cpp.o

.PHONY : SearchFileReader.o

# target to build an object file
SearchFileReader.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/SearchFileReader.cpp.o
.PHONY : SearchFileReader.cpp.o

SearchFileReader.i: SearchFileReader.cpp.i

.PHONY : SearchFileReader.i

# target to preprocess a source file
SearchFileReader.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/SearchFileReader.cpp.i
.PHONY : SearchFileReader.cpp.i

SearchFileReader.s: SearchFileReader.cpp.s

.PHONY : SearchFileReader.s

# target to generate assembly for a file
SearchFileReader.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/SearchFileReader.cpp.s
.PHONY : SearchFileReader.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... ForwardSearchFifoQueue.o"
	@echo "... ForwardSearchFifoQueue.i"
	@echo "... ForwardSearchFifoQueue.s"
	@echo "... Parameters.o"
	@echo "... Parameters.i"
	@echo "... Parameters.s"
	@echo "... Search.o"
	@echo "... Search.i"
	@echo "... Search.s"
	@echo "... SearchFileReader.o"
	@echo "... SearchFileReader.i"
	@echo "... SearchFileReader.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

